// Curated lucide icon registry. Importing named icons (instead of the whole
// `icons` map) keeps the unused ~1,500 icons out of the bundle; dynamic
// name lookups go through this map. When using a new icon in a component,
// add its kebab-case name here.
import {
  Activity,
  ArrowLeft,
  ArrowRight,
  Box,
  Calculator,
  Calendar,
  CalendarDays,
  ChartColumn,
  ChartColumnIncreasing,
  Check,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  CircleCheckBig,
  CircleDollarSign,
  Clock,
  Copy,
  Database,
  DatabaseZap,
  FileText,
  Gauge,
  History,
  Info,
  KeyRound,
  LayoutDashboard,
  List,
  LockKeyhole,
  Maximize2,
  Monitor,
  Moon,
  Pencil,
  Plug,
  Plus,
  Power,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Server,
  ServerCog,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  ShieldOff,
  Shuffle,
  Sun,
  Tag,
  Timer,
  Trash2,
  TriangleAlert,
  User,
  Wallet,
  WandSparkles,
  Workflow,
  X,
} from "lucide";

export const iconRegistry = {
  activity: Activity,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  box: Box,
  calculator: Calculator,
  calendar: Calendar,
  "calendar-days": CalendarDays,
  "chart-column": ChartColumn,
  "chart-column-increasing": ChartColumnIncreasing,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "circle-check": CircleCheck,
  "circle-check-big": CircleCheckBig,
  "circle-dollar-sign": CircleDollarSign,
  clock: Clock,
  copy: Copy,
  database: Database,
  "database-zap": DatabaseZap,
  "file-text": FileText,
  gauge: Gauge,
  history: History,
  info: Info,
  "key-round": KeyRound,
  "layout-dashboard": LayoutDashboard,
  list: List,
  "lock-keyhole": LockKeyhole,
  "maximize-2": Maximize2,
  monitor: Monitor,
  moon: Moon,
  pencil: Pencil,
  plug: Plug,
  plus: Plus,
  power: Power,
  "refresh-cw": RefreshCw,
  "rotate-ccw": RotateCcw,
  save: Save,
  search: Search,
  server: Server,
  "server-cog": ServerCog,
  settings: Settings,
  "settings-2": Settings2,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shield-off": ShieldOff,
  shuffle: Shuffle,
  sun: Sun,
  tag: Tag,
  timer: Timer,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  user: User,
  wallet: Wallet,
  "wand-sparkles": WandSparkles,
  workflow: Workflow,
  x: X,
};
