version: 2

project_name: gomodel

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/gomodel
    ldflags:
      - -s -w
      - -X gomodel/internal/version.Version={{.Version}}
      - -X gomodel/internal/version.Commit={{.Commit}}
      - -X gomodel/internal/version.Date={{.Date}}

archives:
  - formats: ['tar.gz']
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: ['zip']

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  use: github
  sort: asc
  abbrev: -1
  filters:
    exclude:
      - "^docs:"
      - "^doc:"
      - "^Docs:"
      - "^test:"
      - "^tests:"
      - "^refactor:"
      - "^ci:"
      - "^chore:"
      - "^build:"
      - "^style:"
      - "^perf:"
      - "^Revert"
      - "^Merge"

release:
  footer: |
    **Full Changelog**: https://github.com/ENTERPILOT/GOModel/compare/{{ .PreviousTag }}...{{ .Tag }}
