package litellmmigrate

import (
	"fmt"
	"slices"
	"strconv"
	"strings"
)

// envFile collects the environment the generated config needs: values the
// converter moved out of the LiteLLM config (written to the .env file) and
// variables the LiteLLM config already read from the environment (which the
// operator must keep providing).
type envFile struct {
	names    []string
	values   map[string]string
	required []string
	// reserved holds every variable the LiteLLM config reads, explicitly
	// with os.environ/ or implicitly as a provider's default key variable.
	// Generated names never take one, so a moved secret cannot shadow a value
	// another setting reads.
	reserved map[string]bool
}

// reserve marks name as owned by the operator's environment.
func (e *envFile) reserve(name string) {
	if e.reserved == nil {
		e.reserved = map[string]bool{}
	}
	e.reserved[name] = true
}

// taken reports whether name is reserved or already holds a value.
func (e *envFile) taken(name string) bool {
	_, hasValue := e.values[name]
	return hasValue || e.reserved[name]
}

// set records a value under name and returns the name actually used, which
// gets a numeric suffix when name is reserved or holds a different value.
func (e *envFile) set(name, value string) string {
	if e.values == nil {
		e.values = map[string]string{}
	}
	candidate := name
	for i := 2; ; i++ {
		existing, hasValue := e.values[candidate]
		switch {
		case hasValue && existing == value:
			return candidate
		case !hasValue && !e.reserved[candidate]:
			e.values[candidate] = value
			e.names = append(e.names, candidate)
			return candidate
		}
		candidate = fmt.Sprintf("%s_%d", name, i)
	}
}

// unset removes name and its value, if written.
func (e *envFile) unset(name string) {
	delete(e.values, name)
	e.names = slices.DeleteFunc(e.names, func(n string) bool { return n == name })
}

func (e *envFile) require(name string) {
	if !slices.Contains(e.required, name) {
		e.required = append(e.required, name)
	}
}

// render returns the .env file contents, or nil when there is nothing to
// write.
func (e *envFile) render() []byte {
	if len(e.names) == 0 {
		return nil
	}
	var b strings.Builder
	b.WriteString("# Generated by `gomodel migrate litellm` from values that were inline in the\n")
	b.WriteString("# LiteLLM config. It contains secrets: keep it out of version control.\n")
	b.WriteString("# Load it with GoModel's .env loader or Docker Compose env_file: docker run\n")
	b.WriteString("# --env-file reads values literally and would keep their quotes.\n")
	for _, name := range e.names {
		fmt.Fprintf(&b, "%s=%s\n", name, quoteEnvValue(e.values[name]))
	}
	return []byte(b.String())
}

// quoteEnvValue quotes values a dotenv parser would otherwise split, truncate,
// or expand. Single quotes keep everything literal (including $ and JSON
// escapes); a value that itself holds a single quote falls back to double
// quotes with $ escaped.
func quoteEnvValue(value string) string {
	if value != "" && !strings.ContainsAny(value, " \t\"'#$\\\n=`") {
		return value
	}
	if !strings.ContainsAny(value, "'\n") {
		return "'" + value + "'"
	}
	return strings.ReplaceAll(strconv.Quote(value), "$", `\$`)
}
