package litellmmigrate

import (
	"bytes"
	"fmt"
	"path/filepath"

	"go.yaml.in/yaml/v3"
)

// Result is the outcome of converting one LiteLLM config.
type Result struct {
	// Config is the GoModel config.yaml.
	Config []byte
	// Env is the .env file holding values that were inline in the LiteLLM
	// config. It is nil when there are none.
	Env []byte
	// Report lists what was converted, changed, and left behind.
	Report *Report
	// DatabaseURL is general_settings.database_url with any os.environ/
	// reference resolved, or "" when the config sets none.
	DatabaseURL string
	// MasterKey is general_settings.master_key resolved the same way. It is
	// the admin key of the migrated GoModel.
	MasterKey string
}

// ConvertFile converts the LiteLLM proxy config at path, following its
// include: directives.
func ConvertFile(path string) (*Result, error) {
	src, err := loadFile(path, 0)
	if err != nil {
		return nil, err
	}
	return convert(src, filepath.Base(path))
}

func convert(src *liteLLMConfig, source string) (*Result, error) {
	c := newConverter(src, source)
	c.run()

	var body bytes.Buffer
	fmt.Fprintf(&body, "# Generated by `gomodel migrate litellm` from %s.\n", source)
	body.WriteString("# Review MIGRATION_REPORT.md before switching traffic.\n")
	encoder := yaml.NewEncoder(&body)
	encoder.SetIndent(2)
	if err := encoder.Encode(c.out); err != nil {
		return nil, fmt.Errorf("render GoModel config: %w", err)
	}
	if err := encoder.Close(); err != nil {
		return nil, fmt.Errorf("render GoModel config: %w", err)
	}

	for _, name := range c.env.required {
		if _, written := c.env.values[name]; !written {
			c.report.RequiredEnv = append(c.report.RequiredEnv, name)
		}
	}
	c.report.WrittenEnv = c.env.names
	return &Result{
		Config:      body.Bytes(),
		Env:         c.env.render(),
		Report:      &c.report,
		DatabaseURL: c.setting("database_url"),
		MasterKey:   c.setting("master_key"),
	}, nil
}
